services:
    _defaults:
        bind:
            PoP\LooseContracts\LooseContractManagerInterface: '@loose_contract_manager'

    loose_contract_manager:
        class: \PoP\LooseContracts\LooseContractManager
        public: true

    loose_contract_name_resolver:
        class: \PoP\LooseContracts\NameResolver
        public: true

